# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Detctl < Formula
  desc "The control plane of deterministic skills for AI agents"
  homepage "https://github.com/vieolo/detctl"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Vieolo/detctl/releases/download/v0.0.2/detctl_Darwin_x86_64.tar.gz"
      sha256 "dd23bff1676752e488bd1e35719d38c7cccb073c218d4aff4197bc589342afee"

      define_method(:install) do
        bin.install "detctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Vieolo/detctl/releases/download/v0.0.2/detctl_Darwin_arm64.tar.gz"
      sha256 "0c8618ffb2bf4564b915449838c24acd22b7352449137a453fff44d5b01f0d08"

      define_method(:install) do
        bin.install "detctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vieolo/detctl/releases/download/v0.0.2/detctl_Linux_x86_64.tar.gz"
      sha256 "f5fe17eab5d1b45616e0c6872046e7f0de906a4a128bb61fb79b31c704258064"
      define_method(:install) do
        bin.install "detctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vieolo/detctl/releases/download/v0.0.2/detctl_Linux_arm64.tar.gz"
      sha256 "8ad9a531be536b14779899d189cdb094069e6224155095f5a5b6c462c407b749"
      define_method(:install) do
        bin.install "detctl"
      end
    end
  end
end
