# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uch < Formula
  desc "Universal Command Helper — store, encrypt, and run your re-used terminal commands by nickname."
  homepage "https://github.com/vieolo/uch"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Vieolo/uch/releases/download/v0.2.0/uch_Darwin_x86_64.tar.gz"
      sha256 "0cf0bdffb5d4971a2c057727e8ab8a7560c9fe1fcffef609c8cb492b3207f4e7"

      define_method(:install) do
        bin.install "uch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Vieolo/uch/releases/download/v0.2.0/uch_Darwin_arm64.tar.gz"
      sha256 "26d916f637e539063d38a91044d2e618b4d875bd76fcff6bad14ac865a95dc26"

      define_method(:install) do
        bin.install "uch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vieolo/uch/releases/download/v0.2.0/uch_Linux_x86_64.tar.gz"
      sha256 "9f50cfa2d724ca08b7257bf794a9176c5041e41a940ab8deded972551ba1c852"
      define_method(:install) do
        bin.install "uch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vieolo/uch/releases/download/v0.2.0/uch_Linux_arm64.tar.gz"
      sha256 "8058b2b1ccc4b33945e9aeb7b14637549ea55ccc877dd466d6eb5b60353ab746"
      define_method(:install) do
        bin.install "uch"
      end
    end
  end

  test do
    system "#{bin}/uch", "version"
  end
end
